import React, { createContext, useReducer } from "react";

const secretNumberGenerator = () => {
  return Math.floor(Math.random() * 20) + 1;
};
interface IReducerState {
  showSecretNumber: boolean;
  displayMessage: string;
  secretNumber: number;
  inputValue: number;
  highScore: number;
  score: number;
}

const initReducerState: IReducerState = {
  displayMessage: "Start Guessing...",
  showSecretNumber: false,
  secretNumber: secretNumberGenerator() || 6, // This should be generated by a random function
  inputValue: 0,
  highScore: 0,
  score: 20,
};

export interface todoContextObj {
  state: IReducerState;
  dispatch: React.Dispatch<reducerAction>;
}

export const InputContext = createContext<todoContextObj>({
  state: initReducerState,
  dispatch: () => {},
});

export const enum REDUCER_ACTION_TYPE {
  CHECK,
  RESTART,
  SETINPUT,
}

type reducerAction = {
  type: REDUCER_ACTION_TYPE;
  payload?: number;
};

function reducerFn(state: IReducerState, action: reducerAction): IReducerState {
  switch (action.type) {
    case REDUCER_ACTION_TYPE.CHECK:
      let { highScore, inputValue, score, secretNumber } = state;
      let tempState: IReducerState = state;

      if (inputValue === secretNumber) {
        tempState = {
          ...state,
          showSecretNumber: true,
          displayMessage: "🎉 Correct Number!",
          highScore: score > highScore ? score : highScore,
        };
      }

      if (inputValue !== secretNumber) {
        if (score > 1) {
          tempState = {
            ...state,
            displayMessage: inputValue < secretNumber ? "Too low" : "Too high",
            score: score - 1,
          };
        } else {
          tempState = {
            ...state,
            displayMessage: "💥 You lost the game!",
            score: 0,
          };
        }
      }

      return tempState;

    case REDUCER_ACTION_TYPE.SETINPUT:
      return { ...state, inputValue: action.payload! };

    case REDUCER_ACTION_TYPE.RESTART:
      return {
        ...initReducerState,
        secretNumber: secretNumberGenerator(),
        highScore: state.highScore,
      };

    default:
      throw new Error("Unknown action type");
  }
}

export const InputContextProvider = (props: any) => {
  const [state, dispatch] = useReducer(reducerFn, initReducerState);

  const contextValue: todoContextObj = {
    state,
    dispatch,
  };

  return (
    <InputContext.Provider value={contextValue}>
      {props.children}
    </InputContext.Provider>
  );
};
